### ISSUE TITLE
No toolbar is shown if YII_DEBUG is set to false

### ISSUE THREAD

**Issue by mytskine** [malyshev/yii-debug-toolbar#28] opened 2011-11-03 15:14 UTC
If the constant YII_DEBUG is set to false, then the debug toolbar is initialized (its JS is loaded) but it is not shown (no HTML).
Tested on a fresh install of Yii 1.1.8 whith the latest code for yii-debug-toolbar.

**Comment by malyshev** [comment] 2011-12-26 12:57
Cannot reproduce. Please check may already fixed.

**Comment by malyshev** [comment] 2013-12-10 14:41
Closed as outdated

**Closed as completed by malyshev** 2013-12-10 14:41 UTC
