### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stamm** [malyshev/yii-debug-toolbar#47] opened 2012-01-31 08:38 UTC
Hello, install this extension, but get error:

PHP Error
Trying to get property of non-object
yii-debug-toolbar/yii-debug-toolbar/views/yii_debug_toolbar.php(9)

**Comment by malyshev** [comment] 2013-12-10 14:32
closed as duplicate of #53

**Closed as completed by malyshev** 2013-12-10 14:32 UTC
