### ISSUE TITLE
YiiDebugToolbarPanelSql for SQL Server

### ISSUE THREAD

**Issue by heukirne** [malyshev/yii-debug-toolbar#90] opened 2013-08-23 20:47 UTC
The function getServerInfo() don't work for sqlsrv driver.
The $serverInfo in function was an array for sqlsrv and broke the explode call.

My fix:

```
//$lines = explode('  ', $serverInfo);
//foreach($lines as $line) {
//list($key, $value) = explode(': ', $line, 2);
foreach($serverInfo as $key => $value) {
    $info[YiiDebug::t($key)] = $value;
}
```

**Comment by malyshev** [comment] 2013-12-10 14:25
Closed as duplicate of #97

**Closed as completed by malyshev** 2013-12-10 14:25 UTC
